server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30s
    read: 15s
    write: 10s
    idle: 5s

smtpConfig:
    serverHostName: "smtp.gmail.com"                     # set your SMTP server here
    serverMailAddress: "example@gmail.com"               # set your valid mail address here